<a href="https://colab.research.google.com/github/michal-uszko/pad_cwiczenia/blob/main/pad_lab7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import plotly.graph_objects as go
import plotly.express as px
import statsmodels.formula.api as smf

### Zadanie 1

$\mathbf{H_{0}}$: Nie ma istotnej różnicy w ocenie końcowej pomiędzy uczniami i uczennicami

$\mathbf{H_{a}}$: Istnieje istotna różnica (bez wskazania kierunku) w ocenie końcowej pomiędzy uczniami i uczennicami.

Wczytanie danych

In [ ]:
grades_data = pd.read_csv('/content/drive/MyDrive/PAD/lab7/wyniki.csv')
grades_data

    plec  ocena_koncowa
0      F              6
1      F              6
2      F             10
3      F             15
4      F             10
..   ...            ...
352    M              9
353    M             16
354    M              7
355    M             10
356    M              9

[357 rows x 2 columns]

Uczennice

In [ ]:
female_grades = grades_data['ocena_koncowa'][grades_data['plec'] == 'F']
pd.DataFrame(female_grades)

     ocena_koncowa
0                6
1                6
2               10
3               15
4               10
..             ...
343             15
344             10
349             10
350              6
351              8

[185 rows x 1 columns]

Uczniowie

In [ ]:
male_grades = grades_data['ocena_koncowa'][grades_data['plec'] == 'M']
pd.DataFrame(male_grades)

     ocena_koncowa
5               15
6               11
8               19
9               15
12              14
..             ...
352              9
353             16
354              7
355             10
356              9

[172 rows x 1 columns]

Obliczenie T-statystyki dla dwóch zmiennych (uczennice i uczniowie)

In [ ]:
# Uczennice
female_std = np.std(female_grades)
female_mean = np.mean(female_grades)
female_n = female_grades.shape[0]

# Uczniowe
male_std = np.std(male_grades)
male_mean = np.mean(male_grades)
male_n = male_grades.shape[0]

# T-statystyka
t_statistic = (female_mean - male_mean) / (np.sqrt((np.power(female_std, 2) / female_n) + (np.power(male_std, 2) / male_n)))
print("t-statistic:", t_statistic)

t-statistic: -1.9440943008790124

Obliczenie P-value (liczba stopni swobody dla mniejszej próbki, czyli liczebność próbki uczniów minus jeden)

In [ ]:
df = male_n - 1

p = stats.t.sf(abs(t_statistic), df=df)
print("p-value:", p)

p-value: 0.026762601108434474

Według założeń poziom istotności: $\alpha=0.05$\
Obliczona wartość prawdopodobieństwa (p-value): $p≈0.027$\
\
Ponieważ $p\leq\alpha$, odrzucamy hipotezę zerową $\mathbf{H_{0}}$.\
\
Oznacza to, że **istnieje istotna różnica (bez wskazania kierunku) w ocenie końcowej pomiędzy uczniami i uczennicami.**

### Zadanie 2

In [ ]:
zyski_data = pd.read_csv('/content/drive/MyDrive/PAD/lab7/ZyskiFirmyX.csv')
zyski_data

      Rok  Zysk
0    1821  1645
1    1822   658
2    1823  1926
3    1824   865
4    1825   764
..    ...   ...
195  2016   988
196  2017   895
197  2018  -178
198  2019   543
199  2020   316

[200 rows x 2 columns]

In [ ]:
px.scatter(zyski_data, "Rok", "Zysk", title="Zyski w latach 1821-2020")

In [ ]:
model = smf.ols(formula="Zysk ~ Rok", data=zyski_data).fit()

In [ ]:
zyski_data["fitted"] = model.fittedvalues

fig = go.Figure()
fig.add_trace(go.Scatter(
    x=zyski_data["Rok"], y=zyski_data["Zysk"], name="Zyski - wartości rzeczywiste", mode="markers"))
fig.add_trace(go.Scatter(
    x=zyski_data["Rok"], y=zyski_data["fitted"], name="Zyski - wartości przewidywane"))
fig.update_layout(title="Zyski w latach 1821-2020", xaxis_title="Rok",
    yaxis_title="Zyski")
fig.show()

In [ ]:
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   Zysk   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.005
Method:                 Least Squares   F-statistic:                   0.09357
Date:                Tue, 17 Jan 2023   Prob (F-statistic):              0.760
Time:                        20:24:04   Log-Likelihood:                -1521.3
No. Observations:                 200   AIC:                             3047.
Df Residuals:                     198   BIC:                             3053.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   1373.8795   1150.888      1.194      0.234    -895.692    3643.452
Rok           -0.1832      0.599     -0.306      0.760      -1.364       0.998
==============================================================================
Omnibus:                        0.585   Durbin-Watson:                   2.058
Prob(Omnibus):                  0.746   Jarque-Bera (JB):                0.628
Skew:                          -0.128   Prob(JB):                        0.730
Kurtosis:                       2.900   Cond. No.                     6.39e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.39e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

Z wykresu widać niewielki trend spadkowy, jednakże jest on znikomy, prawie niezauważalny. Oznacza to, że model regresji liniowej wyjaśnia wariancję zmiennej objaśnianej **Zysk** praktycznie tak samo dobrze jak wartość średnia.\
\
Wnioski te pokrywają się z podsumowaniem modelu, w którym **p-value** dla zmiennej **Rok** jest bardzo duże ($P=0.76$). Jest to wartość dużo większa od zazwyczaj zakładanego poziomu istotności ($α=0.05$), więc postawienie hipotezy zerowej ($\mathbf{H_{0}}$ : Zmienna niezależna **Rok** lepiej wyjaśnia wariancję zmiennej zależnej **Zysk** niż wartość średnia) skończyłoby się jej odrzuceniem.

### Zadanie 3

In [ ]:
spending_data = pd.read_csv('/content/drive/MyDrive/PAD/lab7/spendingscores.csv')
spending_data

     Gender  Age  AnnualIncome  SpendingScore
0      Male   19            15             39
1      Male   21            15             81
2    Female   20            16              6
3    Female   23            16             77
4    Female   31            17             40
..      ...  ...           ...            ...
195  Female   35           120             79
196  Female   45           126             28
197    Male   32           126             74
198    Male   32           137             18
199    Male   30           137             83

[200 rows x 4 columns]

In [ ]:
gender_codes = {"Female": 0, "Male": 1}

to_replace = {"Gender": gender_codes}
spending_data = spending_data.replace(to_replace)

In [ ]:
spending_data

     Gender  Age  AnnualIncome  SpendingScore
0         1   19            15             39
1         1   21            15             81
2         0   20            16              6
3         0   23            16             77
4         0   31            17             40
..      ...  ...           ...            ...
195       0   35           120             79
196       0   45           126             28
197       1   32           126             74
198       1   32           137             18
199       1   30           137             83

[200 rows x 4 columns]

In [ ]:
model_3 = smf.ols(formula="SpendingScore ~ Gender + Age + AnnualIncome", data=spending_data).fit()
print(model_3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          SpendingScore   R-squared:                       0.109
Model:                            OLS   Adj. R-squared:                  0.095
Method:                 Least Squares   F-statistic:                     7.960
Date:                Tue, 17 Jan 2023   Prob (F-statistic):           4.91e-05
Time:                        20:24:04   Log-Likelihood:                -922.05
No. Observations:                 200   AIC:                             1852.
Df Residuals:                     196   BIC:                             1865.
Df Model:                           3
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       73.9300      6.642     11.130      0.000      60.831      87.029
Gender          -2.0132      3.512     -0.573      0.567      -8.939       4.913
Age             -0.6004      0.125     -4.806      0.000      -0.847      -0.354
AnnualIncome     0.0079      0.066      0.119      0.905      -0.123       0.139
==============================================================================
Omnibus:                       11.059   Durbin-Watson:                   3.448
Prob(Omnibus):                  0.004   Jarque-Bera (JB):                6.033
Skew:                          -0.233   Prob(JB):                       0.0490
Kurtosis:                       2.288   Cond. No.                         291.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
print("Model P Values:", model_3.pvalues.values)
print("Model Coef:", model_3.params.values)
print("Model Std Errs:", model_3.bse.values)

Model P Values: [1.28775203e-22 5.67117187e-01 3.05517724e-06 9.05093933e-01]
Model Coef: [ 7.39300336e+01 -2.01323375e+00 -6.00371040e-01  7.92939510e-03]
Model Std Errs: [6.64225287 3.51182541 0.12491583 0.06641961]

In [ ]:
spending_data.corr()

                 Gender       Age  AnnualIncome  SpendingScore
Gender         1.000000  0.060867      0.056410      -0.058109
Age            0.060867  1.000000     -0.012398      -0.327227
AnnualIncome   0.056410 -0.012398      1.000000       0.009903
SpendingScore -0.058109 -0.327227      0.009903       1.000000

In [ ]:
px.imshow(spending_data.corr(), color_continuous_scale='viridis', title="Correlation heatmap of Spending Scores dataframe")

In [ ]:
def prune_models(dataframe, response_col_name):
    init_formula_string = response_col_name + " ~ "
    
    cols_no_response = dataframe.columns.tolist()
    cols_no_response.remove(response_col_name)
    rest_of_formula_string = " + ".join(cols_no_response)
    
    formula_string = init_formula_string + rest_of_formula_string

    model_init = smf.ols(formula_string, data=dataframe).fit()
    
    pvalues = model_init.pvalues
    
    max_p = pvalues.idxmax()
    
    alpha = 0.05
    
    # Gdybyśmy chcieli kolejno usuwać najmniej znaczące zmienne aż do momentu, że żadna z nich nie ma p-value > 0.05
    # while pvalues.max() > alpha:
    #     max_p = pvalues.idxmax()
    #     cols_no_response.remove(max_p)
    
    #     rest_of_formula_string = " + ".join(cols_no_response)
    #     formula_string = init_formula_string + rest_of_formula_string
        
    #     model = smf.ols(formula_string, data=dataframe).fit()
    #     pvalues = model.pvalues
    #     pvalues = pvalues.drop("Intercept")

    # Pojedyncza iteracja
    max_p = pvalues.idxmax()
    cols_no_response.remove(max_p)
    
    rest_of_formula_string = " + ".join(cols_no_response)
    formula_string = init_formula_string + rest_of_formula_string
        
    model = smf.ols(formula_string, data=dataframe).fit()
    pvalues = model.pvalues
    pvalues = pvalues.drop("Intercept")    
        
    return model
    
fitted_model = prune_models(spending_data, "SpendingScore")
print(fitted_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          SpendingScore   R-squared:                       0.109
Model:                            OLS   Adj. R-squared:                  0.099
Method:                 Least Squares   F-statistic:                     11.99
Date:                Tue, 17 Jan 2023   Prob (F-statistic):           1.22e-05
Time:                        20:24:04   Log-Likelihood:                -922.05
No. Observations:                 200   AIC:                             1850.
Df Residuals:                     197   BIC:                             1860.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     74.4089      5.281     14.089      0.000      63.994      84.824
Gender        -1.9892      3.497     -0.569      0.570      -8.886       4.908
Age           -0.6006      0.125     -4.821      0.000      -0.846      -0.355
==============================================================================
Omnibus:                       10.935   Durbin-Watson:                   3.447
Prob(Omnibus):                  0.004   Jarque-Bera (JB):                5.938
Skew:                          -0.227   Prob(JB):                       0.0514
Kurtosis:                       2.289   Cond. No.                         128.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.